### PR TITLE
Color Roles action

### PR DESCRIPTION
**Pull request by SnowyJaguar1034**
- This is a...
  - [ ] Superaction    
  - [ x] Action
  - [ ] Snippet
- [ x] I have followed the Guidelines for Contributing as closely as possible.
- [ x] I have thoroughly tested my (super)action and ensured that it works properly, even when used incorrectly.
- [ x] My action is not a wrapper/alias for another command - it has an actual use.

--------------------------------------------------------------------------------
First commit of the SnowuJagaur-ColorRoles/ColorRoles-Command action series.

I know the scripts probably not the best. I'm new to creating scripts like this. In fact (at least to me) this is basically the entire purpose of the color chan bot packed down into 5 commands. I think I did fairly well for my first command. Can't forget Dark, TheBruhFoundation and Can eh dian who offering their advice in #support-1.

### CODE REVIEW

**Comment by SnowyJaguar1034** [comment]
Apologies, I added my action to fun and brian later told me it should be in misc. What should I do about this, if anything?

**Comment by Shylke** [comment]
Yesterday we talked in Atlas and you said you wanted to make some improvements first before merging, is it still the case? Just so I (and the other staff know when to review it).

**Comment by SnowyJaguar1034** [comment]
> Yesterday we talked in Atlas and you said you wanted to make some improvements first before merging, is it still the case? Just so I (and the other staff) know when to review it.
> 
> Edit: just checked the repo and saw it's in the `Fun` section, so I'm assuming you still need to make changes.

Hi, yeah I do have some updates to make on it. I'm planning on doing those this weekend. I assume I need to move it from fun into Misc, which I will do once I have made my changes.

**Comment by SnowyJaguar1034** [comment]
Hello all 👋

This action is ready for review

I have made the changes I was planning on. There was some stuff I couldn't add due to limitations in my knowledge of actions as well as limitations within this current version of Atlas and so any other additions to this I will publish via snippets as/when they are ready.

Just adding a comment informing you it's ready for review per Draco's advice

**Comment by DracoClaw** [comment]
Hey there. So, I could not even begin to review this action as it has some issues that prevent it from working.

- Extra `.` in the action file name
- The when imported the action comes disabled
- The command trigger is set to `colour-test` when the readme states its `color`
- Running the command by itself does not bring up a help command, and running the help subcommand results in an uncaught error
- Also just so you are aware, Tags inside a `{note}` still run

**Comment by SnowyJaguar1034** [comment]
> Hey there. So, I could not even begin to review this action as it has some issues that prevent it from working.
> 
> * Extra `.` in the action file name
> * The when imported the action comes disabled
> * The command trigger is set to `colour-test` when the readme states its `color`
> * Running the command by itself does not bring up a help command, and running the help subcommand results in an uncaught error
> * Also just so you are aware, Tags inside a `{note}` still run

I will look into those fixes for you 😅

**Comment by SnowyJaguar1034** [comment]
Okay I followed @DracoClaw's feedback and have now updated it, again. It should 🤞be ready for review now.

**Comment by DracoClaw** [comment]
- Change the `.action` name to follow the Repo Format Requirements. `ColorRoles-Command.action`
- Running `any command or subcommand provides `Use -color help to get help with color roles.` in addition to the expected output.
- You have coded the credits using your ID, but if you do not share the same server it errors out the embed field, please either `{catch}` it or hardcode it.
- Running `a!color =` and `a!color remove` with no secondary arg goes through instead of erroring.
- The `a!color list` subcommand does not seem to work at all, resulting in an error `embed.author.icon_url: Scheme "{user.avatarurl-error1-no-user-matching-your-search}" is not supported. Scheme must be one of ('http', 'https').`
- Running `a!color = X` with `X` being any number I've set results in a message saying its not a valid number. It also has a very long blank space before the error message.
- The `a!color delete` subcommand does not actually support the role numbers, even though the help embed says it does.

**Comment by SnowyJaguar1034** [comment]
Those previous issues were caused by a mix-up of the files. I almost had them fixed and then I stupidly tried to tweak the delete command to allow users to delete color roles using their shortened numbers, which broke parts of the action.

I also saw that Shylke had a very similar (and probably better) action, even if it lacked some of the features of mine. I'll (probably) come back to it in the future to try to fix it but atm I just cba, it's caused me a lot of hassle.

**Pull request closed without merging**
