### PR TITLE
Chores

### PR DESCRIPTION
**Pull request by DracoClaw**
I updated the DiceRoll Help embed to take advantage of the `{guild.prefix}{message.label}` tags. 

Changed StickyMessage to an embed and using the `--returnId` flag to prevent it from bugging out.

### CODE REVIEW

**Comment by BrianWasTaken** [comment]
I suppose `{message.label}` returns the current trigger of the command, right?

**Comment by Shylke** [comment]
`{message.label}` returns the command's name. If you have an action called `a!roll`, `{message.label}` would return `roll`.

**Comment by DracoClaw** [comment]
I've significantly updated the DiceRoll command. New command formatting as well as a new feature. Please someone test it out to be merged.

**Comment by JaM3141** [comment]
terrible, delet this

**Comment by JaM3141** [comment]
The StickyMessage changes look fairly minor, and as far as I can tell the DiceRoll works good in my testing.

**Pull request merged**
