### PR TITLE
ColorMe command

### PR DESCRIPTION
**Pull request by Shylke**
- This is a...
  - [ ] Superaction    
  - [x] Action
  - [ ] Snippet
- [x] I have followed the Guidelines for Contributing as closely as possible. 
- [x] I have thoroughly tested my (super)action and ensured that it works properly, even when used incorrectly.
- [x] My action is not a wrapper/alias for another command - it has an actual use.

--------------------------------------------------------------------------------

Draco convinced me to share this, lol

everything you need to know is in the `README.MD`

### CODE REVIEW

**Comment by Shylke** [comment]
Oh, just a thing, if this ends up being merged, could you guys remove my legacy `Shylke-Color` action, since it's included in this one?

**Comment by DracoClaw** [comment]
Fuck off StaleBot

**Comment by DracoClaw** [comment]
Nothing action breaking but im gonna be annoying here
- So if you set the color key at the top to `{set;color;}` it sends a embed stating "Role Removed" but also stating that "No color was removed or added"
- running the `a!colorme` command to remove your color gives the same embed when you have no colors, maybe an embed stating this could be nice
- having an arg for the colorme command that is not a valid colr removes your current color instead of yelling that its not valid
- having more | in the color key than there are ids, outputs on the list command a higher role count than there are ids set
- adding ID that are not for a role such as a user or channel id, states `@deleted-role` in the list command, could be nice if it yeets em
- adding something that is not an ID to the key will still output as text in the list command
- having an arg for the hex command that is not a valid hex outputs a random one, maybe say "Hey thats not a hex code! Here have a random one" or something
- is it possible to number these and have the numbers as name options or is that to much to ask?

<3

**Comment by Shylke** [comment]
* Already fixed locally. Btw, it actually was action breaking because `a!colorme list` would break

* Tweaked the msg a little because otherwise I'd have to recode the whole give and take away the role process and I like it as it is too much to recode it from scratch https://shylke.is-fucking.gay/f/SaxZpH

* `a!colorme` alone already does that and doesnt yell at you if you actually have a color, even if you input an invalid color, https://shylke.is-fucking.gay/f/nav738
https://shylke.is-fucking.gay/f/9Yi757
... unless you want an alias like `a!colorme decolor`, which I guess, sure

* Already fixed locally.

* I'll see what I can do, doesn't sound easy

* Again, I'll see what I can do

* ... did you even read `a!colorme help`? It clearly states it there

* The only way I can see achieving this is either hard coding every number near the role ID, and have some wacky `{find}`s which is yucky, or using ArgSplitter, which stops working after 9 args, and I'm fairly sure whoever is going to use this will have the whole fucking rainbow in their color lists, so not gonna happen unless I find a better way to do it

**Comment by DracoClaw** [comment]
> * Tweaked the msg a little because otherwise I'd have to recode the whole give and take away the role process and I like it as it is too much to recode it from scratch https://shylke.is-fucking.gay/f/SaxZpH

The issue is that the embed Title says "Role Removed" and the description says "no role removed"

> * `a!colorme` alone already does that and doesnt yell at you if you actually have a color, even if you input an invalid color, https://shylke.is-fucking.gay/f/nav738
https://shylke.is-fucking.gay/f/9Yi757
... unless you want an alias like `a!colorme decolor`, which I guess, sure

I mean, running the colorme command with an arg you expect to be given a role, so if the arg is not valid it shouldnt remove your role, it should error out. doing this shouldnt remove your role
https://micro.sylo.digital/f/0E4MoT.png

> * ... did you even read `a!colorme help`? It clearly states it there

Yes i know how it works. and that its intended to give a random one, im saying more an easter egg stating that the arg you gave wasnt a valid hex and that instead you are being given a random one
https://micro.sylo.digital/f/lTEz7N.png

**Comment by Shylke** [comment]
Fixed everything said above + fixed another bug where the give/take away color commands didn't work if you had an extra `|` at the end.

**Comment by Shylke** [comment]
weeewooo weeewoooo added support for 19 digit ids as well

**Comment by JaM3141** [comment]
@DracoClaw if you want to review this, go for it. Because I am lost between all of these conversations. If not, close it.

**Comment by DracoClaw** [comment]
ah, didnt realize it got an update, ill have a look at it tonight

**Comment by DracoClaw** [comment]
@Shylke Literally the only issue I could find, I've set 5 roles, and its telling me there are 18 available. I'm also not able to test the 19 digit ID's but I'm sure it works.

**Comment by Shylke** [comment]
Fixed.

In case anyone else besides Draco was curious what the problem was: I was replacing the `|` and any other non IDs with nothing, making the IDs mash together, with the new 19 digits support, the `{find}` was getting the first 1-2 digits from the next ID, and mashing it with the previous, leaving 16 numbers behind altogether, which were counted by `{length}`. This is why Draco was getting 18 roles while he only added 3.

The fix was this: `{length;{replace;{replace;{replace;{get;colorlist};\D;-};(\d{17,19});+};-;}}`, in other words, have Atlas replace all non IDs with `-`, so that the IDs are separated, once the IDs get replaced with `+`s, the `-`s get removed as well, hopefully giving the accurate number of roles.

**Pull request merged**
