### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by BruhDark**
- This is a...
  - [x] Superaction    
  - [ ] Action
  - [ ] Snippet
- [x] I have followed the Guidelines for Contributing as closely as possible.
- [x] I have thoroughly tested my (super)action and ensured that it works properly, even when used incorrectly.
- [x] My action is not a wrapper/alias for another command - it has an actual use.

--------------------------------------------------------------------------------

### CODE REVIEW

**Comment by Shylke** [comment]
Hey, first of all, I'd like to say that your action is really impressive. I love how you incorporate the default Support Role set through the Ticket plugin in your action, and how you managed to make the `a!ts setup` owner-only! The way you use the `{channel.awaitMessage}` tag is remarkable, too.

Unfortunately, your action doesn't follow our [folder format requirements](https://github.com/sylo-digital/community-actions#folder-format-requirements) as is. All of your actions, including the `README.md` file, should be in a folder called `Dark-TicketSystem` (if you don't know how to make folders in GitHub, please check [this](https://github.community/t/add-a-folder/2304)), and that folder should be in the `Tickets` folder. As of now, your actions are randomly placed in the latter folder. 



I've also noticed that you used `setted` as a past tense of `set` in your action (specifically the first and last messages of your `a!setup` subcommand), which is incorrect; it should be `set` ([source](https://www.usingenglish.com/reference/irregular-verbs/set.html)). Yes, I'm that much of a grammar nazi.

**Comment by Shylke** [comment]
Edited my previous comment to add the validator issue.

**Comment by BruhDark** [comment]
Got it, I am going to update the files.

**Comment by BruhDark** [comment]
I have added the abort setup process if ID's are not correct. I have corrected the grammar mistakes for "setted" to "set" and other typos or extra words that I forgot from prompts. Also, added that if the owner does not have the support role, still can use all the commands without needing it, because before it was not possible.

**Comment by JaM3141** [comment]
@BruhDark Labeling this PR an inactive for now. If it's ready to be re-reviewed, let us know. If you're still making changes, you can submit them within 30 days. After 30 days, this PR will be closed and you will have to make a new one.

**Comment by BruhDark** [comment]
@JaM3141 Everything should be correct and updated now, feel free to review it when you are able to.

**Comment by Shylke** [comment]
Tested the action again and found no other issues, will be merging it and closing the pull request.

**Pull request merged**
