### PR TITLE
Dank Memer Giveaway / Heist Actions

### PR DESCRIPTION
**Pull request by Canehdian**
- This is a...
  - [ ] Superaction    
  - [x] Action
  - [ ] Snippet
- [x] I have followed the Guidelines for Contributing as closely as possible.
- [x] I have thoroughly tested my (super)action and ensured that it works properly, even when used incorrectly.
- [x] My action is not a wrapper/alias for another command - it has an actual use.

--------------------------------------------------------------------------------

### CODE REVIEW

**Comment by JaM3141** [comment]
heck off stalebot

**Review by JaM3141 — CHANGES_REQUESTED** [review]
Heist action is great. I have only one complaint with the giveaway action: It does not have an embedded help message when running `a!giveaway help` as per **point 3** in the **Guidelines for Contributing**. Add one and I'll merge it.

**Comment by JaM3141** [comment]
Actually Shylke brought something to my attention as well with the heist action that I didn't experience at first but I am now. It seems that if you provide an invalid role for the `[requirement]`, it *does* error but after the error message disappears, it outputs the heist embed with a `{role.mention-ERROR1-no-role-matching-your-search}` afterwards.

**Comment by Canehdian** [comment]
Added a!giveaway help and updated the heist action to error properly

**Review by JaM3141 — APPROVED** [review]
Looks good

**Pull request merged**
